import {
  CheckSquare,
  LayoutDashboard,
  Bell,
  ClipboardList,
  Calendar,
  CalendarDays,
  PartyPopper,
  Sliders,
  Plane,
  TrendingUp,
  Briefcase,
  FileText,
  ShoppingBag,
  ShoppingCart,
  Package,
  Users,
  UserCheck,
  Target,
  Workflow,
  Truck,
  DollarSign,
  FileSpreadsheet,
  CheckCircle2,
  Users2,
  Boxes,
  ArrowLeftRight,
  FileCheck,
  Clock,
  Database,
  ShieldCheck,
  Building,
  Building2,
  PlusCircle,
  CreditCard,
  PackageCheck,
  Archive,
  Receipt,
  Navigation,
  UserPlus,
  UserX,
  LogOut,
  Award,
  BarChart3,
  Wallet,
  ArrowDownLeft,
  ArrowUpRight,
  Landmark,
  Files,
  AlertTriangle,
  RefreshCw,
  MessageSquare,
  Bookmark,
  Radio,
  Settings,
  ListTodo
} from 'lucide-react';

export const SYSTEMS_CONFIG = [
  {
    id: 'checklist',
    name: 'Checklist & Delegation',
    shortName: 'Checklist & Delegation',
    badge: 'Operations & SOPs',
    description: 'Task delegation, recurring checklists & daily operations',
    icon: CheckSquare,
    color: 'indigo',
    gradient: 'from-indigo-600 to-purple-600',
    bgLight: 'bg-indigo-50 dark:bg-indigo-950/40 text-indigo-600 dark:text-indigo-400',
    border: 'border-indigo-200 dark:border-indigo-800',
    defaultPath: '/checklist/dashboard',
    navItems: [
      { label: 'Checklist Dashboard', path: '/checklist/dashboard', icon: LayoutDashboard },
      { label: 'My Tasks', path: '/my-tasks', icon: CheckSquare },
      { label: 'Task Assignment', path: '/task-assignment', icon: ClipboardList, requiresSelfAssignOrManager: true },
      { label: 'Checklist Templates', path: '/checklist/list', icon: ListTodo, requiresSelfAssignOrManager: true },
      { label: 'Delegations', path: '/delegation/list', icon: UserCheck, requiresSelfAssignOrManager: true },
      { label: 'Calendar', path: '/calendar', icon: Calendar },
      { label: 'Masters', path: '/masters', icon: Sliders, adminOnly: true },
    ]
  },
  {
    id: 'sales',
    name: 'Order To Delivery',
    shortName: 'Order To Delivery',
    badge: 'Revenue & CRM',
    description: 'Leads, Quotations, Sales Orders & Customer Relations',
    icon: TrendingUp,
    color: 'emerald',
    gradient: 'from-emerald-500 to-teal-600',
    bgLight: 'bg-emerald-50 dark:bg-emerald-950/40 text-emerald-600 dark:text-emerald-400',
    border: 'border-emerald-200 dark:border-emerald-800',
    defaultPath: '/sales/dashboard',
    navItems: [
      { label: 'Dashboard', path: '/sales/dashboard', icon: LayoutDashboard },
      { label: 'New Order', path: '/sales/new-order', icon: PlusCircle },
      { label: 'Order Verification', path: '/sales/verification', icon: ShieldCheck },
      { label: 'Order Approval', path: '/sales/approval', icon: FileCheck },
      { label: 'Advance Payment', path: '/sales/advance-payment', icon: DollarSign },
      { label: 'Stock Check', path: '/sales/stock-check', icon: Boxes },
      { label: 'Order Processing', path: '/sales/processing', icon: Workflow },
      { label: 'Quality Check (QC)', path: '/sales/qc', icon: CheckCircle2 },
      { label: 'Ready for Dispatch', path: '/sales/ready-dispatch', icon: PackageCheck },
      { label: 'Dispatch', path: '/sales/dispatch', icon: Truck },
      { label: 'Delivered', path: '/sales/delivered', icon: Package },
      { label: 'Payment Collection', path: '/sales/payment-collection', icon: CreditCard },
      { label: 'Order Closed', path: '/sales/closed', icon: Archive },
    ]
  },
  {
    id: 'master-system',
    name: 'Master System',
    shortName: 'Master System',
    badge: 'Core Masters',
    description: 'Centralized master data for Vendors, Products, Transporters, Users & TAT',
    icon: Sliders,
    color: 'rose',
    gradient: 'from-rose-500 to-pink-600',
    bgLight: 'bg-rose-50 dark:bg-rose-950/40 text-rose-600 dark:text-rose-400',
    border: 'border-rose-200 dark:border-rose-800',
    defaultPath: '/master-system/overview',
    navItems: [
      { label: 'Master Overview', path: '/master-system/overview', icon: LayoutDashboard },
      { label: 'Our Company Details', path: '/master-system/company-details', icon: Building2 },
      { label: 'Vendors Master', path: '/master-system/vendors', icon: Users2 },
      { label: 'Product Master', path: '/master-system/products', icon: Package },
      { label: 'Department Master', path: '/master-system/departments', icon: Building },
      { label: 'User / Employee Master', path: '/master-system/users', icon: UserCheck },
      { label: 'TAT Management', path: '/master-system/tat', icon: Clock },
      { label: 'Working Day Calendar', path: '/master-system/working-calendar', icon: CalendarDays },
      { label: 'Holidays Master', path: '/master-system/holidays', icon: Calendar },
    ]
  },
  {
    id: 'purchase',
    name: 'Purchase System',
    shortName: 'Purchase',
    badge: 'Procurement',
    description: 'Purchase indents, PO issuance, lifting, delivery, QC, GRN & payments',
    icon: ShoppingCart,
    color: 'amber',
    gradient: 'from-amber-500 to-orange-600',
    bgLight: 'bg-amber-50 dark:bg-amber-950/40 text-amber-600 dark:text-amber-400',
    border: 'border-amber-200 dark:border-amber-800',
    defaultPath: '/purchase/indent',
    navItems: [
      { label: 'Purchase Indent', path: '/purchase/indent', icon: FileText },
      { label: 'Indent Approval', path: '/purchase/indent-approval', icon: CheckSquare },
      { label: 'PO', path: '/purchase/po', icon: FileSpreadsheet },
      { label: 'Material Lifting / Dispatch', path: '/purchase/lifting-dispatch', icon: Truck },
      { label: 'Material Delivery', path: '/purchase/delivery', icon: Navigation },
      { label: 'Material Receiving', path: '/purchase/receiving', icon: PackageCheck },
      { label: 'Quality Check', path: '/purchase/qc', icon: ShieldCheck },
      { label: 'GRN', path: '/purchase/grn', icon: Receipt },
      { label: 'Payment', path: '/purchase/payment', icon: CreditCard },
    ]
  },
  {
    id: 'lead-to-orders',
    name: 'Lead To Orders',
    shortName: 'Lead-To-Order',
    badge: 'Pipeline & Deals',
    description: 'End-to-end lead qualification to order conversion pipeline',
    icon: Target,
    color: 'violet',
    gradient: 'from-violet-600 to-purple-600',
    bgLight: 'bg-violet-50 dark:bg-violet-950/40 text-violet-600 dark:text-violet-400',
    border: 'border-violet-200 dark:border-violet-800',
    defaultPath: '/lead-to-orders/dashboard',
    navItems: [
      { label: 'Dashboard', path: '/lead-to-orders/dashboard', icon: LayoutDashboard },
      { label: 'Leads', path: '/lead-to-orders/leads', icon: Users },
      { label: 'Follow-up', path: '/lead-to-orders/follow-up', icon: Clock },
      { label: 'Quotation', path: '/lead-to-orders/quotation', icon: FileText },
      { label: 'Negotiation', path: '/lead-to-orders/negotiation', icon: TrendingUp },
      { label: 'Approval', path: '/lead-to-orders/approval', icon: FileCheck },
      { label: 'Reports', path: '/lead-to-orders/reports', icon: FileSpreadsheet },
    ]
  },
  {
    id: 'hr',
    name: 'HR System',
    shortName: 'HR & People',
    badge: 'Human Resources',
    description: 'Complete HR Flow Management System from Requirement to Exit',
    icon: Users,
    color: 'cyan',
    gradient: 'from-cyan-500 to-blue-600',
    bgLight: 'bg-cyan-50 dark:bg-cyan-950/40 text-cyan-600 dark:text-cyan-400',
    border: 'border-cyan-200 dark:border-cyan-800',
    defaultPath: '/hr/dashboard',
    navItems: [
      { label: 'Dashboard', path: '/hr/dashboard', icon: LayoutDashboard, section: 'Overview' },

      // Recruitment
      { label: 'Indent / Requirement', path: '/hr/indent', icon: FileText, section: 'Recruitment' },
      { label: 'Indent Approval', path: '/hr/indent-approval', icon: FileCheck, section: 'Recruitment' },
      { label: 'Job Enquiry', path: '/hr/job-enquiry', icon: Briefcase, section: 'Recruitment' },
      { label: 'Candidate Screening', path: '/hr/candidate-screening', icon: UserCheck, section: 'Recruitment' },
      { label: 'Follow-up / Interview', path: '/hr/interviews', icon: Clock, section: 'Recruitment' },
      { label: 'Offer / Salary Approval', path: '/hr/offer-approval', icon: DollarSign, section: 'Recruitment' },
      { label: 'Joining', path: '/hr/joining', icon: UserPlus, section: 'Recruitment' },

      // Employee
      { label: 'Active Employees', path: '/hr/active-employees', icon: Users, section: 'Employee' },
      { label: 'Inactive Employees', path: '/hr/inactive-employees', icon: UserX, section: 'Employee' },

      // Attendance & Leave
      { label: 'Attendance', path: '/hr/attendance', icon: CheckSquare, section: 'Attendance & Leave' },
      { label: 'Leave', path: '/hr/leave', icon: Plane, section: 'Attendance & Leave' },

      // Payroll
      { label: 'Payroll', path: '/hr/payroll', icon: DollarSign, section: 'Payroll' },
      { label: 'Payslips', path: '/hr/payslips', icon: Receipt, section: 'Payroll' },

      // Exit Management
      { label: 'Resignation', path: '/hr/resignation', icon: LogOut, section: 'Exit Management' },
      { label: 'Exit / Clearance', path: '/hr/clearance', icon: ShieldCheck, section: 'Exit Management' },
      { label: 'Full & Final Settlement', path: '/hr/fnf', icon: CreditCard, section: 'Exit Management' },

      // Documents & Letters
      { label: 'Employee Documents', path: '/hr/documents', icon: Archive, section: 'Documents & Letters' },
      { label: 'HR Letters', path: '/hr/letters', icon: Award, section: 'Documents & Letters' },

      // Reports
      { label: 'Reports', path: '/hr/reports', icon: FileSpreadsheet, section: 'Reports' },
    ]
  },
  {
    id: 'petty-expenses',
    name: 'Petty Expenses',
    shortName: 'Petty Expenses',
    badge: 'Cash & Cheques',
    description: 'Petty Cash Inflow, Outgoings, Expense Vouchers & Cheque Deposit/Clearance Tracker',
    icon: Wallet,
    color: 'teal',
    gradient: 'from-teal-500 to-emerald-600',
    bgLight: 'bg-teal-50 dark:bg-teal-950/40 text-teal-600 dark:text-teal-400',
    border: 'border-teal-200 dark:border-teal-800',
    defaultPath: '/petty-expenses/dashboard',
    navItems: [
      { label: 'Overview & Ledger', path: '/petty-expenses/dashboard', icon: LayoutDashboard },
      { label: 'Amount Received (In)', path: '/petty-expenses/received', icon: ArrowDownLeft },
      { label: 'Expenses (Out)', path: '/petty-expenses/outgoings', icon: ArrowUpRight },
      { label: 'Cheque Tracker', path: '/petty-expenses/cheques', icon: Landmark },
      { label: 'Reports & Analytics', path: '/petty-expenses/reports', icon: FileSpreadsheet },
    ]
  },
  {
    id: 'doc-subscription',
    name: 'Document & Subscription',
    shortName: 'Docs & Subscriptions',
    badge: 'Compliance & SaaS',
    description: 'Corporate Documents, Legal Agreements, SaaS Subscriptions, Renewal Pipeline & Payment Tracker',
    icon: Files,
    color: 'blue',
    gradient: 'from-blue-600 to-indigo-600',
    bgLight: 'bg-blue-50 dark:bg-blue-950/40 text-blue-600 dark:text-blue-400',
    border: 'border-blue-200 dark:border-blue-800',
    defaultPath: '/doc-subscription/dashboard',
    navItems: [
      { label: 'Dashboard', path: '/doc-subscription/dashboard', icon: LayoutDashboard },

      // Documents
      { label: 'All Documents', path: '/doc-subscription/documents?tab=all', icon: FileText, section: 'Documents' },
      { label: 'Add Document', path: '/doc-subscription/documents?tab=add', icon: PlusCircle, section: 'Documents' },
      { label: 'Pending Verification', path: '/doc-subscription/documents?tab=pending', icon: ShieldCheck, section: 'Documents' },
      { label: 'Expiring Soon', path: '/doc-subscription/documents?tab=expiring', icon: Clock, section: 'Documents' },
      { label: 'Expired', path: '/doc-subscription/documents?tab=expired', icon: AlertTriangle, section: 'Documents' },

      // Subscriptions
      { label: 'All Subscriptions', path: '/doc-subscription/subscriptions?tab=all', icon: CreditCard, section: 'Subscriptions' },
      { label: 'Add Subscription', path: '/doc-subscription/subscriptions?tab=add', icon: PlusCircle, section: 'Subscriptions' },
      { label: 'Renewal Due', path: '/doc-subscription/subscriptions?tab=renewalDue', icon: Clock, section: 'Subscriptions' },
      { label: 'Payment Due', path: '/doc-subscription/subscriptions?tab=paymentDue', icon: DollarSign, section: 'Subscriptions' },
      { label: 'Expired', path: '/doc-subscription/subscriptions?tab=expired', icon: AlertTriangle, section: 'Subscriptions' },

      // Renewal & Expiry
      { label: 'Renewal & Expiry', path: '/doc-subscription/renewals', icon: RefreshCw, section: 'Management' },

      // Payment Tracking
      { label: 'Payment Tracking', path: '/doc-subscription/payments', icon: Receipt, section: 'Management' },

      // History
      { label: 'History', path: '/doc-subscription/history', icon: Archive, section: 'Management' },
    ]
  },
  {
    id: 'whatsapp',
    name: 'WhatsApp Inbox',
    shortName: 'WhatsApp',
    badge: 'Live Chat & CRM',
    description: 'WhatsApp Live Chat, Message Composer, Customer ERP Context, Canned Templates & Webhook Engine',
    icon: MessageSquare,
    color: 'emerald',
    gradient: 'from-emerald-500 to-green-600',
    bgLight: 'bg-emerald-50 dark:bg-emerald-950/40 text-emerald-600 dark:text-emerald-400',
    border: 'border-emerald-200 dark:border-emerald-800',
    defaultPath: '/whatsapp/inbox',
    navItems: [
      { label: 'WhatsApp Inbox', path: '/whatsapp/inbox', icon: MessageSquare, section: 'Live Chats' },
      { label: 'Broadcast & Templates', path: '/whatsapp/templates', icon: Bookmark, section: 'Messaging' },
      { label: 'API & Webhooks', path: '/whatsapp/settings', icon: Settings, section: 'Configuration' },
    ]
  },
  {
    id: 'mis-summary',
    name: 'MIS Summery',
    shortName: 'MIS Summery',
    badge: 'Scoring & TAT',
    description: 'Executive MIS Summary, User Performance Scoring & Planned vs Actual TAT Analytics',
    icon: Award,
    color: 'indigo',
    gradient: 'from-blue-600 to-indigo-600',
    bgLight: 'bg-indigo-50 dark:bg-indigo-950/40 text-indigo-600 dark:text-indigo-400',
    border: 'border-indigo-200 dark:border-indigo-800',
    defaultPath: '/mis-summary',
    navItems: [
      { label: 'MIS Summery & Scoring', path: '/mis-summary', icon: Award, section: 'Executive' },
      { label: 'User Performance Report', path: '/mis-summary?view=users', icon: BarChart3, section: 'Executive' },
      { label: 'Task Delay Audit', path: '/mis-summary?view=tasks', icon: Clock, section: 'Executive' },
    ]
  },
  {
    id: 'inventory',
    name: 'Inventory System',
    shortName: 'Inventory',
    badge: 'Stock & Warehouse',
    description: 'Real-time stock ledger, multi-warehouse tracking, inward/outward flow & reorder alerts',
    icon: Boxes,
    color: 'orange',
    gradient: 'from-orange-500 to-amber-600',
    bgLight: 'bg-orange-50 dark:bg-orange-950/40 text-orange-600 dark:text-orange-400',
    border: 'border-orange-200 dark:border-orange-800',
    defaultPath: '/inventory/dashboard',
    navItems: [
      { label: 'Dashboard', path: '/inventory/dashboard', icon: LayoutDashboard },
      { label: 'In / Out', path: '/inventory/in-out', icon: ArrowLeftRight },
      { label: 'Indent', path: '/inventory/indent', icon: ShoppingCart },
    ]
  }
];
